deploy:
  artifact: deploy.zip
branch-defaults:
  deploy-dynamic-docker-compose:
    environment: docker-elastic-beanstalk-up-dev
global:
  application_name: docker-elastic-beanstalk-up
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
