name: api

on:
  push:
    branches: ["ci"]

  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: docker-elastic-beanstalk-up
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        id: configure-aws
        uses: ./actions/configure-aws

      - name: Sending API Docker image
        env:
          REGISTRY: ${{ steps.configure-aws.outputs.registry }}
          PACKAGE_NAME: api
          REPOSITORY: docker-elastic-beanstalk-up
        run: yarn push-docker

      - name: DeployðŸ¤ž
        run: yarn deploy
