name: Deploy

on:
  push:
    tags: "**"

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: docker-elastic-beanstalk-up
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        id: configure-aws
        uses: ./.github/actions/configure-aws
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: Sending API Docker image
        env:
          REGISTRY: ${{ steps.configure-aws.outputs.ecr-registry }}
          REPOSITORY: docker-elastic-beanstalk-up
        run: yarn push-docker

      - name: Deploying to EB
        uses: actions/checkout@v4
        env:
          REGISTRY: ${{ steps.configure-aws.outputs.ecr-registry }}
          REPOSITORY: docker-elastic-beanstalk-up
        run: yarn deploy
