name: On Pull Request

on:
  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  version:
    name: Version and tag new versions
    runs-on: ubuntu-latest
    environment: docker-elastic-beanstalk-up
    steps:
      - name: Version
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DOCKER_ELASTIC_BEANSTALK_VERSION_UP }}
          fetch-depth: 0
      - run: |
          yarn
          git config user.name "${{ github.actor }}"
          yarn lerna exec test
