name: Test

on:
  push:
    branches: ["include-lerna"]

  workflow_dispatch:

jobs:
  deploy:
    if: ${{ !contains(github.event.head_commit.message, 'Publish') }}
    name: deploy
    runs-on: ubuntu-latest
    environment: docker-elastic-beanstalk-up
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Version
        uses: actions/checkout@v3
        # with:
        #   token: ${{ secrets.DOCKER_ELASTIC_BEANSTALK_VERSION_UP }}
        #   fetch-depth: 0
      - run: |
          yarn
          git config user.name "${{ github.actor }}"
          git config user.email "wellington.grisa@gmail.com"
          yarn lerna version --conventional-commits --no-commit-hooks --yes --include-merged-tags

      # - name: Checkout
      #   uses: actions/checkout@v3

      - name: Configure AWS
        id: configure-aws
        uses: ./.github/actions/configure-aws
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      # - name: Sending API Docker image
      #   env:
      #     REGISTRY: ${{ steps.configure-aws.outputs.ecr-registry }}
      #     REPOSITORY: docker-elastic-beanstalk-up
      #   run: yarn lerna run build-docker --ignore models --since

      - name: Update docker compose?
        run: yarn update-docker-compose
